# Generated by Django 3.1.3 on 2020-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name of the external services', max_length=128)),
                ('secret_auth_token', models.CharField(editable=False, help_text='Secret for authentication. Will be automaticly generated.', max_length=256)),
            ],
        ),
    ]
