# Generated by Django 3.1.3 on 2020-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployclientmodel',
            name='name',
            field=models.CharField(help_text='Service name of the external services', max_length=128, unique=True),
        ),
    ]
