# Generated by Django 3.1.3 on 2020-11-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_django', '0002_auto_20201121_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployclientmodel',
            name='name',
            field=models.CharField(db_index=True, help_text='Service name of the external services', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='DeployRequestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challange', models.CharField(max_length=256)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy_django.deployclientmodel')),
            ],
        ),
    ]
